webApp:
  replicaCount: 1

  image:
    repository: beratcloudnativeacr.azurecr.io/web-app
    tag: 5de38d6509dd0d95f6303f45fa3aa748b9be393f
    pullPolicy: IfNotPresent

  orderServiceUrl: http://order-service:8080

  service:
    port: 3000

  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi