webApp:
  replicaCount: 2

  image:
    repository: beratcloudnativeacr.azurecr.io/web-app
    tag: 2bd0923ee89023abe8954055759981f3e64b47fe
    pullPolicy: IfNotPresent

  orderServiceUrl: http://order-service:8080

  service:
    port: 3000

  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
  
  imagePullSecrets:
    - name: acr-pull-secret

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 60
    behavior:
      scaleDown:
        stabilizationWindowSeconds: 60

  vpa:
    enabled: false
    updateMode: "Off"

  rollout:
    enabled: false
    revision: analysis-query-v2
    stableService: web-app-stable
    canaryService: web-app-canary
    virtualService: platform-ingress
    virtualServiceRoute: web-app-primary
    analysisTemplate: web-app-5xx-rate
    prometheusAddress: http://monitoring-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
    errorRateThreshold: 0.05
    simulateFailure: false
