apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  labels:
    app: web-app
    app.kubernetes.io/name: web-app
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:

  
  replicas: {{.Values.webApp.replicaCount }}
  selector:
    matchLabels:
      app: web-app
      version: v1
  template:

    
    metadata:
      labels:
        app: web-app
        version: v1
        app.kubernetes.io/name: web-app
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      imagePullSecrets:
        {{- toYaml .Values.webApp.imagePullSecrets | nindent 8 }}
      containers:
        - name: web-app
          image: "{{ .Values.webApp.image.repository }}:{{ .Values.webApp.image.tag }}"
          imagePullPolicy: {{ .Values.webApp.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000

          # securityContext ile container için güvenlik önlemleri alındı
          #örneğin readOnlyRootFilesystem: true ile containerın root dosya sistemine yazma izni engellendi
          # runAsNonRoot ve runAsUser:1000 ile containerın root kullanıcısı olarak çalışması engellendi ve 1000 UID ile çalışması sağlandı
          # allowPrivilegeEscalation: sınırlı kullanıcıdan root'a yükselme engellendi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
          
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          env:
            - name: ORDER_SERVICE_URL
              value: {{ .Values.webApp.orderServiceUrl | quote }}
          resources:
{{ toYaml .Values.webApp.resources | indent 12 }}