apiVersion: v1
kind: Service
metadata:
  name: web-app
  labels:
    app: web-app
spec:
  ports:
    - port: {{ .Values.webApp.service.port }}
      targetPort: http
      name: http
  selector:
    app: web-app