orderService:
  image:
    repository: beratcloudnativeacr.azurecr.io/order-service
    pullPolicy: IfNotPresent
  versions:
    - name: v1
      tag: v1-3adfc4cf4517f52adcc89338d2fbfe1de128f4e6
      replicaCount: 1
    - name: v2
      tag: v2-3adfc4cf4517f52adcc89338d2fbfe1de128f4e6
      replicaCount: 1
  userServiceUrl: http://user-service:8080
  database:
    host: postgresql
    port: 5432
    name: orders
    poolMax: 5
    connectionTimeoutMs: 3000
    existingSecret:
      name: postgres-credentials
      usernameKey: username
      passwordKey: password
  service:
    port: 8080
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 128Mi
  imagePullSecrets:
    - name: acr-pull-secret
