# bu dosya Azure KeyVault'taki secret'ları kullanarak Kubernetes Secret oluşturur, ESO tarafından kullanılır
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-credentials
  namespace: demo
spec:
  # 1 dakikada bir KeyVault'ta değişiklik var mı diye kontrol eder, vault ta parola değişirse Kubernetes Secret otomatik güncellenir
  refreshPolicy: Periodic
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: azure-key-vault
  target:
    name: postgres-credentials
    # k8s secret'ı ESO oluşturur ve sahiplenir external secret silinirse k8s secret da silinir
    creationPolicy: Owner
    # keyvault taki geçici bir hatada k8s secret hemen silinmesin elimdekini koru demek deletionPolicy: Retain
    deletionPolicy: Retain
  #datamapping sayesinde k8s secret key-value çiftlerini keyvault'taki secret key-value çiftleri ile eşleştiriyoruz
  data:
    - secretKey: username
      remoteRef:
        key: postgres-username
    - secretKey: password
      remoteRef:
        key: postgres-password