# secret store dosyası sayesinde ESO'ya Azure Key Vault'a nasıl bağlancağını söylüyoruz
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: azure-key-vault
  namespace: demo
spec:
  provider:
    azurekv:
      authType: ServicePrincipal
      environmentType: PublicCloud
      vaultUrl: "https://kv-berat-cloudnative.vault.azure.net"
      tenantId: "7459e3d8-331f-4966-9689-66db0e347029"
      authSecretRef:
      # burada clientId ve clientSecret bilgilerini hangi secret'tan alacağını söylüyoruz.
        clientId:
          name: azure-keyvault-credentials
          key: client-id
        clientSecret:
          name: azure-keyvault-credentials
          key: client-secret