postgresql:
  replicaCount: 1
  image:
    repository: postgres
    tag: "18-alpine"
    digest: "sha256:d3e1620b530c944afa6e887d22eb899824da68e19c52024bf98f5220c88a65b2"
    pullPolicy: IfNotPresent

  database:
    name: orders

  existingSecret:
    name: postgres-credentials
    usernameKey: username
    passwordKey: password

  service:
    name: postgresql
    type: ClusterIP
    port: 5432
    headless: true

  persistence:
    storageClassName: standard
    size: 1Gi
    mountPath: /var/lib/postgresql/data
    pgDataSubdir: pgdata
  securityContext:
    runAsUser: 70
    fsGroup: 70
    runAsGroup: 70

  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi

  probes:
    startupPeriodSeconds: 2
    startupFailureThreshold: 30
    initialDelaySeconds: 10
    periodSeconds: 10
