apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-config
  namespace: argocd
spec:
  project: cloud-native-platform
  source:
    repoURL: git@github.com:BeratDgan/cloud-native-order-platform.git
    targetRevision: main
    path: gitops/external-secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=false
      - PruneLast=true