apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: order-service
  namespace: argocd
spec:
  project: cloud-native-platform
  source:
    repoURL: git@github.com:BeratDgan/cloud-native-order-platform.git
    targetRevision: main
    path: helm/order-service
    helm:
      releaseName: order-service
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
      # automated sync ile deploy sırasında kaynaklar otomatik olarak güncellenir
      - Automated=true
      # prune ile yapılan deploy sırasında silinmiş olan kaynaklar otomatik olarak silinir
      - Prune=true
      # selfHeal ile yapılan deploy sırasında silinmiş olan kaynaklar otomatik olarak tekrar oluşturulur
      - SelfHeal=true
      # allowEmpty kapalı olduğundan deploy sırasında kaynaklar silinmişse hata alınır ve deploy başarısız olur
      - AllowEmpty=false
      # CreateNamespace=false ile deploy sırasında namespace yoksa oluşturulmaz ve hata alınır
      - CreateNamespace=false

