apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-app
  namespace: argocd
spec:
  project: cloud-native-platform
  source:
    repoURL: git@github.com:BeratDgan/cloud-native-order-platform.git
    targetRevision: main
    path: helm/web-app
    helm:
      releaseName: web-app
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
