apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-email
  namespace: demo
spec:
  refreshPolicy: Periodic
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: azure-key-vault
  target:
    name: alertmanager-email
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: app-password
      remoteRef:
        key: alertmanager-gmail-app-password
