apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-key-vault
  namespace: demo
  annotations:
    azure.workload.identity/client-id: "7c2b4864-518f-4306-84b5-09c852c801bb"
    azure.workload.identity/tenant-id: "7459e3d8-331f-4966-9689-66db0e347029"